// Tools > GEBOD: the fields of ATB 3I's "GEBOD V.2" form (GEBOD.cs / BdyDim.cs decompile), same order, items and
// defaults. It only collects a GebodRequest; MainForm.Gebod() answers the unmodified Gebodv.exe with it.
using System.Globalization;
using Atb.Core.Cards;
using Atb.Core.Solver;

namespace Atb.App;

public sealed class GebodForm : Form
{
    static readonly string[] Subjects =
    [
        "Child (2 - 19 Years)", "Adult Human Female", "Adult Human Male", "User-Supplied Body Dimensions",
        "Sitting Hybrid III Dummy (50%)", "Standing Hybrid III Dummy (50%)", "Hybrid II Dummy (50%)",
        "Sitting Hybrid III with Lower Extremity Model",
    ];
    // GEBOD.cs range array [ISUB-1, dim (age, weight, height), lo/hi] in the first unit; the second unit divides by Factor.
    static readonly double[,,] Range =
    {
        { { 24, 240 }, { 22.27, 247.6 }, { 32.01, 76.54 } },
        { { 0, 0 }, { 85, 200 }, { 56.93, 72.05 } },
        { { 0, 0 }, { 118, 264 }, { 62.17, 77.64 } },
    };
    static readonly double[] Factor = [12, 0.2248, 39.37];

    readonly ComboBox subject = Combo(Subjects), param = Combo(), output = Combo("English", "Metric"),
        arm = Combo("Forearm and Hand Combined", "Forearm and Hand Separated"), joint = Combo("Standard Joint Property", "Detailed Joint Property Function");
    readonly ComboBox[] units = [Combo("Months", "Years"), Combo(), Combo()];
    readonly TextBox[] values = [new(), new(), new()];
    readonly Label[] ranges = [new() { AutoSize = true }, new() { AutoSize = true }, new() { AutoSize = true }];
    readonly Control[][] dimRows = new Control[3][];
    readonly Button enter = new() { Text = "Enter 32 Body Dimension Data", AutoSize = true };
    readonly TableLayoutPanel t = new() { Dock = DockStyle.Fill, ColumnCount = 3, AutoSize = true, Padding = new Padding(10) };
    double[]? bodyDims; bool metricInput;

    public GebodRequest? Request { get; private set; }
    public double[]? BodyDims => bodyDims;
    public GebodPlacement Placement => new((GebodMode)place.SelectedIndex, (int)body.Value);

    // ATB 3I's warnings, Body.cs:1019 (add), :990 (insert), :1049 (replace).
    public const string AddText = "Add a new body?  ATB 3I will cascade update other input cards for\r\nsegment numbering.  You can't undo this operation after clicking \"Run GEBOD\" button in the next window.";
    public const string InsertText = "Insert a new body before the selected body?\r\nClick NO button will add the body after the selected body.\r\nATB 3I will cascade update other input cards for segment numbering.\r\nYou can't undo this operation after clicking \"Run GEBOD\" button in the next window.";
    public const string ReplaceText = "You are about to replace the selected body with data generated by GEBOD.  ATB3I will\r\nADJUST this body's segment numbers referred on other cards for the difference between the\r\nreplaced and new body.  You can't undo this operation after clicking \"Run GEBOD\" button in the next window.  Continue?";
    readonly ComboBox place = Combo("Add a new body after the last", "Insert before body", "Insert after body", "Replace body");
    readonly NumericUpDown body = new() { Minimum = 1, Maximum = 1, Width = 80 };
    readonly Label warn = new() { AutoSize = true, MaximumSize = new Size(560, 0) };

    /// bodyCount = bodies in the open deck; 0 (an empty deck) only allows Add. preset = the placement Body Summary's
    /// GEBOD buttons chose (3I's GEBOD form has no placement fields then: they are hidden).
    public GebodForm(int bodyCount, GebodPlacement? preset = null)
    {
        Text = "GEBOD V.2"; AutoSize = true; AutoSizeMode = AutoSizeMode.GrowAndShrink; FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox = MinimizeBox = false; StartPosition = FormStartPosition.CenterParent;
        if (bodyCount == 0) while (place.Items.Count > 1) place.Items.RemoveAt(1);
        body.Maximum = Math.Max(bodyCount, 1);
        place.SelectedIndexChanged += (_, _) =>
        {
            var m = (GebodMode)place.SelectedIndex;
            Show(body, m != GebodMode.Add);
            warn.Text = m == GebodMode.Add ? AddText : m == GebodMode.Replace ? ReplaceText : InsertText;
        };
        Row("Place the GEBOD body", place);
        Row("Body number", body);
        t.Controls.Add(warn); t.SetColumnSpan(warn, 3);
        place.SelectedIndex = 0;
        if (preset != null)
        {
            place.SelectedIndex = (int)preset.Mode; body.Value = Math.Clamp(preset.Body, 1, (int)body.Maximum);
            Show(place, false); Show(body, false); warn.Visible = false;
        }
        Row("Subject Type", subject);
        Row("Supplied Parameter", param);
        string[] names = ["Age", "Weight", "Height"];
        for (int i = 0; i < 3; i++)
        {
            var l1 = new Label { Text = "Units for " + names[i], AutoSize = true, Anchor = AnchorStyles.Left };
            var l2 = new Label { Text = names[i], AutoSize = true, Anchor = AnchorStyles.Left };
            t.Controls.Add(l1); t.Controls.Add(units[i]); t.SetColumnSpan(units[i], 2);
            t.Controls.Add(l2); t.Controls.Add(values[i]); t.Controls.Add(ranges[i]);
            dimRows[i] = [l1, units[i], l2, values[i], ranges[i]];
            units[i].AccessibleName = l1.Text; values[i].AccessibleName = names[i];
            int k = i; units[i].SelectedIndexChanged += (_, _) => ShowRange(k);
        }
        Row("Units for Output Data Set", output);
        Row("Lower Arm Segmentation", arm);
        Row("Joint Property Option", joint);
        t.Controls.Add(enter); t.SetColumnSpan(enter, 3);
        var run = new Button { Text = "Run GEBOD", AutoSize = true };
        var cancel = new Button { Text = "Cancel", AutoSize = true, DialogResult = DialogResult.Cancel };
        var buttons = new FlowLayoutPanel { AutoSize = true, FlowDirection = FlowDirection.RightToLeft, Dock = DockStyle.Fill };
        buttons.Controls.AddRange([cancel, run]);
        t.Controls.Add(buttons); t.SetColumnSpan(buttons, 3);
        Controls.Add(t); CancelButton = cancel;

        subject.SelectedIndexChanged += (_, _) => OnSubject();
        param.SelectedIndexChanged += (_, _) => OnParam();
        output.SelectedIndexChanged += (_, _) => OnArmOrOutput();
        arm.SelectedIndexChanged += (_, _) =>
        {
            if (arm.SelectedIndex >= 0 && output.SelectedIndex < 0) { MessageBox.Show(this, "Please make selection for output data set's units first."); arm.SelectedIndex = -1; return; }
            OnArmOrOutput();
        };
        enter.Click += (_, _) =>
        {
            using var d = new BodyDimForm(bodyDims, metricInput);
            if (d.ShowDialog(this) == DialogResult.OK) { bodyDims = d.Dims; metricInput = d.Metric; }
        };
        run.Click += (_, _) => OnRun();
        OnSubject();
    }

    static ComboBox Combo(params string[] items)
    {
        var c = new ComboBox { DropDownStyle = ComboBoxStyle.DropDownList, Width = 300 };
        c.Items.AddRange(items);
        return c;
    }

    void Row(string label, Control c)
    {
        var l = new Label { Text = label, AutoSize = true, Anchor = AnchorStyles.Left };
        t.Controls.Add(l); t.Controls.Add(c); t.SetColumnSpan(c, 2);
        c.Tag = l; c.AccessibleName = label;   // UIA name = the visible label (screen readers, the UI robot)
    }

    static void Show(Control c, bool on) { c.Visible = on; if (c.Tag is Label l) l.Visible = on; }
    int Isub => subject.SelectedIndex + 1;
    int Idim => param.SelectedIndex < 0 ? -1 : param.SelectedItem!.ToString()![0] - '0';

    void OnSubject()
    {
        int s = Isub;
        param.Items.Clear();
        if (s == 1) param.Items.Add("0) Age");
        if (s is >= 1 and <= 3) param.Items.AddRange(["1) Weight", "2) Standing Height", "3) All the Above"]);
        // child: no Percentile unit
        foreach (var (c, items) in new[] { (units[1], new[] { "Lb.", "N.", "Percentile" }), (units[2], new[] { "In.", "M.", "Percentile" }) })
        { c.Items.Clear(); c.Items.AddRange(s == 1 ? items[..2] : items); }
        output.SelectedIndex = arm.SelectedIndex = joint.SelectedIndex = -1;
        Show(param, s is >= 1 and <= 3);
        Show(output, s >= 4);
        Show(enter, s == 4);
        OnParam();
    }

    void OnParam()
    {
        int s = Isub, d = Idim;
        bool[] on = [s == 1 && d is 0 or 3, d is 1 or 3, d is 2 or 3];
        for (int i = 0; i < 3; i++)
        {
            foreach (var c in dimRows[i]) c.Visible = on[i];
            units[i].SelectedIndex = -1; values[i].Text = ""; ranges[i].Text = "";
        }
        if (s is >= 1 and <= 3 && d >= 0) Show(output, true);
        Show(arm, s is 2 or 3 && d >= 0);
        OnArmOrOutput();
    }

    void OnArmOrOutput()
    {
        bool detail = arm.Visible && output.SelectedIndex == 0 && arm.SelectedIndex == 1;
        Show(joint, detail);
        if (!detail) joint.SelectedIndex = -1;
    }

    void ShowRange(int i)
    {
        int u = units[i].SelectedIndex;
        if (u < 0 || Isub is < 1 or > 3) { ranges[i].Text = ""; return; }
        if (u == 2) { ranges[i].Text = "(0 - 100)"; return; }
        double f = u == 0 ? 1 : Factor[i];
        ranges[i].Text = $"({Range[Isub - 1, i, 0] / f:0.###} - {Range[Isub - 1, i, 1] / f:0.###})";
    }

    void OnRun()
    {
        int s = Isub;
        if (s < 1) return;
        if (output.SelectedIndex < 0 && (s >= 4 || Idim >= 0)) { MessageBox.Show(this, "No output unit selection"); return; }
        var m = new GebodMeasure?[3];
        if (s <= 3)
        {
            if (Idim < 0) return;
            for (int i = 0; i < 3; i++)
            {
                if (!units[i].Visible) continue;
                if (units[i].SelectedIndex < 0 || !double.TryParse(values[i].Text, NumberStyles.Float, CultureInfo.InvariantCulture, out var v))
                { MessageBox.Show(this, "Invalid input in textbox."); return; }
                int u = units[i].SelectedIndex;
                double lo = u == 2 ? 0 : Range[s - 1, i, 0] / (u == 0 ? 1 : Factor[i]), hi = u == 2 ? 100 : Range[s - 1, i, 1] / (u == 0 ? 1 : Factor[i]);
                if (v < lo || v > hi) { MessageBox.Show(this, "Input out of range"); return; }
                m[i] = new GebodMeasure(u + 1, v);
            }
            if (arm.Visible && arm.SelectedIndex < 0) { MessageBox.Show(this, "No selection on lower arm segmentation"); return; }
            if (joint.Visible && joint.SelectedIndex < 0) { MessageBox.Show(this, "No selection on joint property option"); return; }
        }
        if (s == 4 && (bodyDims == null || bodyDims.Any(x => x == 0))) { MessageBox.Show(this, "Invalid body dimension input."); return; }

        // GEBOD.cs has no description field; the exe asks for one, so it gets the subject type name.
        var r = new GebodRequest(Subjects[s - 1], s, Math.Max(Idim, 0), m[0], m[1], m[2],
            MetricOutput: output.SelectedIndex == 1, HandSeparated: arm.SelectedIndex == 1, DetailedJoint: joint.SelectedIndex == 1,
            DimensionFile: s == 4 ? "BODYDIM.DAT" : null, MetricInput: metricInput);
        try { Gebod.Answers(r); }   // the exe's own limits (e.g. percentile strictly 1-100) are stricter than GEBOD.cs
        catch (ArgumentException ex) { MessageBox.Show(this, ex.Message); return; }
        Request = r; DialogResult = DialogResult.OK;
    }
}

/// BdyDim.cs "32 Body Dimensions": units combo (English default) and 32 boxes with ATB 3I's defaults.
sealed class BodyDimForm : Form
{
    static readonly (string Name, double Default)[] Fields =
    [
        ("Weight", 551.5768), ("Standing Height", 1.531), ("Shoulder Height", 1.252), ("Armpit Height", 1.166),
        ("Waist Height", 0.878), ("Seated Height", 0.856), ("Head Length", 0.195), ("Head Breadth", 0.146),
        ("Head to Chin Height", 0.212), ("Neck Circumference", 0.315), ("Shoulder Breadth", 0.338), ("Chest Depth", 0.223),
        ("Chest Breadth", 0.284), ("Waist Depth", 0.206), ("Waist Breadth", 0.295), ("Buttock Depth", 0.208),
        ("Hip Breadth, Standing", 0.338), ("Shoulder to Elbow Length", 0.276), ("Forearm-Hand Length", 0.393), ("Biceps Circumference", 0.276),
        ("Elbow Circumference", 0.234), ("Forearm Circumference", 0.246), ("Waist Circumference", 0.153), ("Knee Height, Seated", 0.457),
        ("Thigh Circumference", 0.598), ("Upper Leg Circumference", 0.521), ("Knee Circumference", 0.366), ("Calf Circumference", 0.369),
        ("Ankle Circumference", 0.223), ("Ankle Height, Outside", 0.063), ("Foot Breadth", 0.088), ("Foot Length", 0.229),
    ];
    readonly ComboBox unit = new() { DropDownStyle = ComboBoxStyle.DropDownList, Items = { "English", "Metric" } };
    readonly TextBox[] boxes = new TextBox[32];
    public double[] Dims { get; } = new double[32];
    public bool Metric => unit.SelectedIndex == 1;

    public BodyDimForm(double[]? current, bool metric)
    {
        Text = "32 Body Dimensions"; AutoSize = true; AutoSizeMode = AutoSizeMode.GrowAndShrink; FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox = MinimizeBox = false; StartPosition = FormStartPosition.CenterParent;
        var t = new TableLayoutPanel { Dock = DockStyle.Fill, ColumnCount = 4, AutoSize = true, Padding = new Padding(10) };
        t.Controls.Add(new Label { Text = "Units for Input", AutoSize = true, Anchor = AnchorStyles.Left }); t.Controls.Add(unit); t.SetColumnSpan(unit, 3);
        unit.SelectedIndex = metric ? 1 : 0;
        for (int i = 0; i < 32; i++)
        {
            t.Controls.Add(new Label { Text = Fields[i].Name, AutoSize = true, Anchor = AnchorStyles.Left });
            t.Controls.Add(boxes[i] = new TextBox { Width = 90, Text = (current?[i] ?? Fields[i].Default).ToString(CultureInfo.InvariantCulture) });
        }
        var ok = new Button { Text = "OK", AutoSize = true };
        var cancel = new Button { Text = "Cancel", AutoSize = true, DialogResult = DialogResult.Cancel };
        t.Controls.Add(ok); t.Controls.Add(cancel);
        Controls.Add(t); CancelButton = cancel;
        ok.Click += (_, _) =>
        {
            for (int i = 0; i < 32; i++)
                if (!double.TryParse(boxes[i].Text, NumberStyles.Float, CultureInfo.InvariantCulture, out Dims[i]))
                { MessageBox.Show(this, "Invalid input in textbox."); return; }
            DialogResult = DialogResult.OK;
        };
    }
}
