      SUBROUTINE MSC_DERIVS(NZ, ZZ, MPTS, X, Y, DYDX)
      USE  MODULE_STANDARD,  ONLY:  
     &       INTEGER_STD, IREAL_HIGH, MSC_DIRECTION, I_0, HMAX, ! PARAMETER
     &       LUAOU, G, MXHIC
!C
      IMPLICIT  NONE
!C
      INTEGER ( KIND = INTEGER_STD ) N, NZ, MPTS
      REAL ( KIND = IREAL_HIGH ) ZZ(MXHIC,2), X, Y(2), DYDX(2), HC, HM,  
     &  HK, CV, ACCEL, DELTAT, DZ
!C
!C    COMPUTE RIGHT HAND SIDE OF 2 MSC EQUATIONS FOR DERIVERTIVES 
!C    AT X. USED BY SUBROUTINES RKCK, RKQS, MSC TO SOLVE MSC EQUATIONS.
!C    THE MODEL IS BASED ON R. STALNAKER'S PAPER. ZZ(MPTS,2) IS THE TABULAR 
!C    HEAD LONGITUDINAL OR LATERAL ACCELERATION AT C.G. THE 1ST COLUMN OF ZZ 
!C    IS TIME AND NZ IS THE INDEX TO THE CURRENT TIME POINT IN ZZ.
!C    Y(1) = LONGITUDINAL OR LATERAL DISPLACEMENT BETWEEN SKULL AND BRAIN.
!C    Y(2) = Y(1)'
!C    X = TIME AND HAS TO BE IN UNIT OF SECOND.
!C
      CV = 0.031081          !CONVERSION FACTOR FROM LBF TO SLUGS
      IF (MSC_DIRECTION .EQ. I_0) THEN
!C      LONGITUDINAL HUMAN HEAD MODEL
        HM = 10.0
        HC = 2.0
        HK = 50000.0
      ELSE
        HM = 9.0        
        HC = 2.4
        HK = 26000.0
      END IF
      HM = (HM * CV) / 12.0
      IF (X. LE. ZZ(NZ+1,1)) THEN
        DELTAT = ZZ(NZ+1,1) - ZZ(NZ,1)
        DZ = ZZ(NZ+1,2) - ZZ(NZ,2)
        ACCEL = ZZ(NZ,2) + ((X - ZZ(NZ,1)) / DELTAT) * DZ 
      ELSE 
        DELTAT = ZZ(NZ+2,1) - ZZ(NZ+1,1)
        DZ = ZZ(NZ+2,2) - ZZ(NZ+1,2)
        ACCEL = ZZ(NZ+1,2) + ((X - ZZ(NZ+1,1)) / DELTAT) * DZ 
      END IF
      DYDX(1) = Y(2)
      DYDX(2) = -(HC / HM) * Y(2) - (HK / HM) * Y(1) - ACCEL * G
      RETURN
      END

