      SUBROUTINE RKCK(Y,DYDX,N,X,H,YOUT,YERR,NZ,ZZ,MPTS,DERIVS)
      USE  MODULE_STANDARD,  ONLY:  
     &       INTEGER_STD, IREAL_HIGH, MXHIC                   ! PARAMETER
!C
      IMPLICIT  NONE
!C
      INTEGER ( KIND = INTEGER_STD ) N,NZ,MPTS
      REAL ( KIND = IREAL_HIGH ) H,X,DYDX(N),Y(N),YERR(N),YOUT(N),
     &                           ZZ(MXHIC,2) 
      EXTERNAL DERIVS
!C
!C    ADAPTED FROM FOTRAN NUMERICAL RECIPES. USES SUBROUTINE DERIVS
!C    GIVEN VALUES FOR N VARIABLES Y AND THEIR DERIVATIVES DYDX 
!C    KNOWN AT X, USE THE FIFTH-ORDER CASH-KARP RUNGE-KUTTA METHOD TO 
!C    ADVANCE THE SOLUTION OVER AN INTERVAL H AND RETURN THE INCREMENTED 
!C    VARIABLES AS YOUT. ALSO RETURN AN ESTIMATE OF THE LOCAL TRUNCATION ERROR
!C    IN YOUT USING THE EMBEDDED FOURTH-ORDER METHOD. THE USER SUPPLIES 
!C    THE SUBROUTINE DERIVS(X,Y,DYDX), WHICH RETURNS DERIVATIVES DYDX AT X.
!C    ZZ(MPTS,2) IS A TABULAR EXTERNAL INPUT TO THE ODE. THE 1ST COLUMN OF ZZ 
!C    IS TIME AND NZ IS THE INDEX TO THE CURRENT TIME POINT IN ZZ. ZZ IS USED BY 
!C    DERIVS TO COMPUTE DERIVATIVES. 
!C
      INTEGER ( KIND = INTEGER_STD ) I
      REAL ( KIND = IREAL_HIGH ) AK2(N),AK3(N),AK4(N),
     &  AK5(N),AK6(N),YTEMP(N),A2,A3,A4,A5,A6,B21,B31,
     &  B32,B41,B42,B43,B51, B52,B53,B54,B61,B62,B63,B64,B65,
     &  C1,C3,C4,C6,DC1,DC3, DC4,DC5,DC6
      PARAMETER (A2=.2,A3=.3,A4=.6,A5=1.,A6=.875,B21=.2,B31=3./40.,
     &  B32=9./40.,B41=.3,B42=-.9,B43=1.2,B51=-11./54.,B52=2.5,
     &  B53=-70./27.,B54=35./27.,B61=1631./55296.,B62=175./512.,
     &  B63=575./13824.,B64=44275./110592.,B65=253./4096.,
     &  C1=37./378.,C3=250./621.,C4=125./594.,C6=512./1771.,
     &  DC1=C1-2825./27648.,DC3=C3-18575./48384.,
     &  DC4=C4-13525./55296.,DC5=-277./14336.,DC6=C6-.25)
!C
!C          
      DO I=1,N
        YTEMP(I)=Y(I)+B21*H*DYDX(I)                            !FIRST STEP
      END DO 
      CALL DERIVS(NZ,ZZ,MPTS,X+A2*H,YTEMP,AK2)                 !SECOND STEP
      DO I=1,N
        YTEMP(I)=Y(I)+H*(B31*DYDX(I)+B32*AK2(I))
      END DO
      CALL DERIVS(NZ,ZZ,MPTS,X+A3*H,YTEMP,AK3)                 !THIRD STEP
      DO I=1,N
        YTEMP(I)=Y(I)+H*(B41*DYDX(I)+B42*AK2(I)+B43*AK3(I))
      END DO
      CALL DERIVS(NZ,ZZ,MPTS,X+A4*H,YTEMP,AK4)                 !FOURTH STEP
      DO I=1,N
        YTEMP(I)=Y(I)+H*(B51*DYDX(I)+B52*AK2(I)+B53*AK3(I)+
     &  B54*AK4(I))
      END DO
      CALL DERIVS(NZ,ZZ,MPTS,X+A5*H,YTEMP,AK5)                 !FIFTH STEP
      DO I=1,N
        YTEMP(I)=Y(I)+H*(B61*DYDX(I)+B62*AK2(I)+B63*AK3(I)+
     &  B64*AK4(I)+B65*AK5(I))
      END DO
      CALL DERIVS(NZ,ZZ,MPTS,X+A6*H,YTEMP,AK6)                 !SIXTH STEP
!C    ACCUMULATE INCREMENTS WITH PROPER WEIGHTS.
      DO I=1,N 
        YOUT(I)=Y(I)+H*(C1*DYDX(I)+C3*AK3(I)+C4*AK4(I)+
     &  C6*AK6(I))
      END DO
      DO I=1,N
!C    ESTIMATE ERROR AS DIFFERENCE BETWEEN FOURTH AND FIFTH ORDER METHODS.
      YERR(I)=H*(DC1*DYDX(I)+DC3*AK3(I)+DC4*AK4(I)+DC5*AK5(I)
     &  +DC6*AK6(I))
      END DO
      RETURN
      END