      SUBROUTINE RKQS(Y,DYDX,N,X,HTRY,EPS,YSCAL,HDID,HNEXT,
     &  NZ,ZZ,MPTS,DERIVS)
      USE  MODULE_STANDARD,  ONLY:  
     &       INTEGER_STD, IREAL_HIGH, LUAOU, MXHIC             ! parameter
!C
      IMPLICIT  NONE
!C
      INTEGER ( KIND = INTEGER_STD ) N,NZ,MPTS
      REAL ( KIND = IREAL_HIGH ) EPS,HDID,HNEXT,HTRY,X,DYDX(N),
     &  Y(N),YSCAL(N), ZZ(MXHIC,2)
      EXTERNAL DERIVS
!C
!C    ADAPTED FROM FOTRAN NUMERICAL RECIPES. USES SUBROUTINES DERIVS,RKCK
!C    FIFTH-ORDER RUNGE-KUTTA STEP WITH MONITORING OF LOCAL TRUNCATION ERROR 
!C    TO ENSURE ACCURACY AND ADJUST STEPSIZE. INPUT ARE THE DEPENDENT 
!C    VARIABLE VECTOR Y(1:N) AND ITS DERIVATIVE DYDX(1:N) AT THE STARTING 
!C    VALUE OF THE INDEPENDENT VARIABLE X. ALSO INPUT ARE THE STEPSIZE
!C    TO BE ATTEMPTED HTRY, THE REQUIRED ACCURACY EPS, AND THE VECTOR 
!C    YSCAL(1:N) AGAINST WHICH THE ERROR IS SCALED. ZZ(MPTS,2) IS A TABULAR 
!C    EXTERNAL INPUT TO THE ODE.  THE 1ST COLUMN OF ZZ IS TIME AND NZ IS THE 
!C    INDEX TO THE CURRENT TIME POINT IN ZZ. ZZ IS USED BY DERIVS TO COMPUTE 
!C    DERIVATIVES ON OUTPUT, Y AND X ARE REPLACED BY THEIR NEW VALUES, HDID 
!C    IS THE STEPSIZE THAT WAS ACTUALLY ACCOMPLISHED, AND HNEXT IS THE ESTIMATED 
!C    NEXT STEPSIZE. DERIVS IS THE USER-SUPPLIED SUBROUTINE THAT COMPUTES THE 
!C    RIGHT-HAND SIDE DERIVATIVES.
!C
      INTEGER ( KIND = INTEGER_STD ) I
      REAL ( KIND = IREAL_HIGH ) ERRMAX,H,HTEMP,XNEW,YERR(N),YTEMP(N),
     &  SAFETY,PGROW,PSHRNK,ERRCON
      PARAMETER (SAFETY=0.9,PGROW=-.2,PSHRNK=-.25,ERRCON=1.89E-4)

      H=HTRY
!C    ADVANCE A STEP OF H.
      DO
        CALL RKCK(Y,DYDX,N,X,H,YTEMP,YERR,NZ,ZZ,MPTS,DERIVS)
        ERRMAX=0.
        DO I=1,N
          ERRMAX=MAX(ERRMAX,ABS(YERR(I)/YSCAL(I)))
        END DO
        ERRMAX=ERRMAX/EPS
        IF (ERRMAX.GT.1.) THEN 
!C        TRUNCATION ERROR TOO LARGE, REDUCE STEPSIZE
          HTEMP=SAFETY*H*(ERRMAX**PSHRNK)
!C        NO MORE THEN FACTOR OF 10
          H=SIGN(MAX(ABS(HTEMP),0.1*ABS(H)),H)
          XNEW=X+H
          IF(XNEW.EQ.X) THEN
            WRITE ( LUAOU, 20 ) H, X   
   20       FORMAT('STOP 94 Integration step size underflow in subroutine 
     &        RKQS. H=', 1PD25.15, ' at X=', 1PD25.15)  
            STOP ' STOP 94 in Subroutine RKQS '
          END IF
          CYCLE
        ELSE
!C        STEP SUCCEEDED. COMPUTE SIZE OF NEXT STEP
          IF(ERRMAX.GT.ERRCON)THEN
            HNEXT=SAFETY*H*(ERRMAX**PGROW)
          ELSE 
!C          NO MORE THAN A FACTOR OF 5 INCREASE.
            HNEXT=5.*H
          ENDIF
          HDID=H
          X=X+H
          EXIT
        END IF
      END DO
      DO I=1,N
        Y(I)=YTEMP(I)
      ENDDO
      RETURN
      END